site_name: Documentation Platform
site_url: https://becdeg.com

theme:
  name: material
  palette:
    - scheme: Light
      primary: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  logo: bgm.png
  favicon: beclogo.png
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - extra.css
extra_javascript:
  - https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap

plugins:
  - search
  - tags

nav:
  - Home:
      - The Docs Behind Docs: index.md
      - About Me: aboutme.md
      - Why BECDEG?: whybecdeg.md
  - Experiences: experience.md
  - Services: services.md
  - Contact: contact.md
  - Tags: tags.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
