site_name: Doc Studio
site_url: https://becdeg.com

theme:
  name: material
  palette:
    - scheme: Light
      primary: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  logo: bgm.png
  favicon: beclogo.png
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - extra.css
extra_javascript:
  - https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap

plugins:
  - search
  - tags

nav:
  - Home:
      - The docs behind docs: index.md
      - About me: aboutme.md
      - Why BECDEG?: whybecdeg.md
  - What's new?: Whatsnew.md
  - Documentation:
      - Overview: Documentation_overview.md
      - User manuals: 
          - Overview: user_manuals_overview.md
      - Step by step guides: 
          - Overview: step-by-step-guide-overview.md
          - Download and install MS Teams application: download_and_install_msteams.md
      - How-to guides: 
          - Overview: How_to_overview.md
          - How to schedule a meeting in MS Teams application: schedule_meeting_in_teams.md
      - APIs: 
          - Overview: APIs.md
      - Business user guides: 
          - Overview: business-user-guides.md
      - Case studies: 
          - Overview: case-studies.md
  - Experiences: experience.md
  - Services: services.md
  - Contact: contact.md
  - Tags: tags.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg