site_name: BECDEG
site_url: https://becdeg.com

theme:
  name: material
  palette:
    - scheme: Light
      primary: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  logo: Becdeg logo.png
  favicon: Becdeg logo.png
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - extra.css

plugins:
  - search
  - tags

nav:
  - Home:
      - The Docs Behind Docs: index.md
      - About Me: techdocs.md
  - Tags: tags.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
